language: node_js
node_js:
  - node
script:
  - npm run lint
  - npm test
  - npm run typescript
  - npm run build
  - echo "Folder name in Digital Ocean Spaces - $TRAVIS_COMMIT"
  - mkdir -p dist/login/$TRAVIS_COMMIT
  - mv dist/*.* dist/login/$TRAVIS_COMMIT/
